# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pirate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pirate.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cpirate.proto\"%\n\x07\x43\x61ptain\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04hook\x18\x04 \x01(\x08\"(\n\nCrewMember\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\t\"\xf7\x01\n\x04\x42oat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x07\x63\x61ptain\x18\x02 \x01(\x0b\x32\x08.Captain\x12\x1c\n\x07sailors\x18\x05 \x03(\x0b\x32\x0b.CrewMember\x12-\n\x0fpropulsion_kind\x18\x07 \x01(\x0e\x32\x14.Boat.PropulsionType\x12\x12\n\x08\x63oalType\x18\x08 \x01(\tH\x00\x12\x1a\n\x10plutoniumIsotope\x18\t \x01(\x05H\x00\"1\n\x0ePropulsionType\x12\x08\n\x04WIND\x10\x00\x12\x08\n\x04\x43OAL\x10\x01\x12\x0b\n\x07NUCLEAR\x10\x02\x42\x16\n\x14propulsion_attributeb\x06proto3')
)



_BOAT_PROPULSIONTYPE = _descriptor.EnumDescriptor(
  name='PropulsionType',
  full_name='Boat.PropulsionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WIND', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUCLEAR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=272,
  serialized_end=321,
)
_sym_db.RegisterEnumDescriptor(_BOAT_PROPULSIONTYPE)


_CAPTAIN = _descriptor.Descriptor(
  name='Captain',
  full_name='Captain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Captain.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hook', full_name='Captain.hook', index=1,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=53,
)


_CREWMEMBER = _descriptor.Descriptor(
  name='CrewMember',
  full_name='CrewMember',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CrewMember.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank', full_name='CrewMember.rank', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=95,
)


_BOAT = _descriptor.Descriptor(
  name='Boat',
  full_name='Boat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Boat.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='captain', full_name='Boat.captain', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sailors', full_name='Boat.sailors', index=2,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='propulsion_kind', full_name='Boat.propulsion_kind', index=3,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coalType', full_name='Boat.coalType', index=4,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plutoniumIsotope', full_name='Boat.plutoniumIsotope', index=5,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BOAT_PROPULSIONTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='propulsion_attribute', full_name='Boat.propulsion_attribute',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=98,
  serialized_end=345,
)

_BOAT.fields_by_name['captain'].message_type = _CAPTAIN
_BOAT.fields_by_name['sailors'].message_type = _CREWMEMBER
_BOAT.fields_by_name['propulsion_kind'].enum_type = _BOAT_PROPULSIONTYPE
_BOAT_PROPULSIONTYPE.containing_type = _BOAT
_BOAT.oneofs_by_name['propulsion_attribute'].fields.append(
  _BOAT.fields_by_name['coalType'])
_BOAT.fields_by_name['coalType'].containing_oneof = _BOAT.oneofs_by_name['propulsion_attribute']
_BOAT.oneofs_by_name['propulsion_attribute'].fields.append(
  _BOAT.fields_by_name['plutoniumIsotope'])
_BOAT.fields_by_name['plutoniumIsotope'].containing_oneof = _BOAT.oneofs_by_name['propulsion_attribute']
DESCRIPTOR.message_types_by_name['Captain'] = _CAPTAIN
DESCRIPTOR.message_types_by_name['CrewMember'] = _CREWMEMBER
DESCRIPTOR.message_types_by_name['Boat'] = _BOAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Captain = _reflection.GeneratedProtocolMessageType('Captain', (_message.Message,), dict(
  DESCRIPTOR = _CAPTAIN,
  __module__ = 'pirate_pb2'
  # @@protoc_insertion_point(class_scope:Captain)
  ))
_sym_db.RegisterMessage(Captain)

CrewMember = _reflection.GeneratedProtocolMessageType('CrewMember', (_message.Message,), dict(
  DESCRIPTOR = _CREWMEMBER,
  __module__ = 'pirate_pb2'
  # @@protoc_insertion_point(class_scope:CrewMember)
  ))
_sym_db.RegisterMessage(CrewMember)

Boat = _reflection.GeneratedProtocolMessageType('Boat', (_message.Message,), dict(
  DESCRIPTOR = _BOAT,
  __module__ = 'pirate_pb2'
  # @@protoc_insertion_point(class_scope:Boat)
  ))
_sym_db.RegisterMessage(Boat)


# @@protoc_insertion_point(module_scope)
